START_TIME_PER_TURN = 1000
START_BOARD_WIDTH = 100
START_BOARD_HEIGHT = 100
START_BOARD_SIZE = START_BOARD_WIDTH * START_BOARD_HEIGHT
NUMBER_OF_BACTERIAS_TO_START = 20

DEFAULT_FOOD_PER_TURN = 3
DEFAULT_MUTATION_RATE = 0.1
START_ENERGY = 200

MAX_BACTERIA_SPEED = 15
MAX_BACTERIA_SENSE = 30

MUTATION_CHANGE = 2
ENERGY_FOR_FOOD = 200

SVG_SIZE = 4
BUTTON_SIZE = 35
