START_TIME_PER_TURN = 1000
DEFAULT_FOOD_PER_TURN = 3
DEFAULT_MUTATION_RATE = 0.1
START_ENERGY = 200

MAX_BACTERIA_SPEED = 15
MAX_BACTERIA_SENSE = 30

MUTATION_CHANGE = 2
ENERGY_FOR_FOOD = 200

SVG_SIZE = 4
